const fs = require('node:fs');
const path = require('node:path');
const { buildSync } = require('esbuild');

const root = path.join(__dirname, '..');
const file = path.join(root, 'code-review-checker-2219.html');
const built = buildSync({
  absWorkingDir: root, entryPoints: ['scripts/parser-entry.mjs'], bundle: true,
  format: 'iife', globalName: 'reviewParsers', platform: 'browser', target: 'es2022',
  supported: { 'template-literal': false },
  write: false, metafile: true, legalComments: 'none', minify: true
});
const packages = [...new Set(Object.keys(built.metafile.inputs).flatMap(file => {
  const match = file.match(/^node_modules\/((?:@[^/]+\/)?[^/]+)/);
  return match ? [match[1]] : [];
}))].sort();
const licenses = packages.map(name => {
  const folder = path.join(root, 'node_modules', name);
  const metadata = JSON.parse(fs.readFileSync(path.join(folder, 'package.json'), 'utf8'));
  const licenseName = fs.readdirSync(folder).find(file => /^licen[sc]e(?:\.(?:md|txt))?$/i.test(file));
  if (!licenseName) throw new Error(`Missing license for ${name}`);
  return `${name} ${metadata.version}\n${fs.readFileSync(path.join(folder, licenseName), 'utf8').replace(/\r\n?/g, '\n').trimEnd()}`;
}).join('\n\n');
const parser = built.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const embedded = `  <!-- BEGIN EMBEDDED ACORN -->\n  <script id="review-parser">\n/* Acorn ${require('acorn/package.json').version} and Java parsers — generated by scripts/embed-parser.cjs.\n${licenses.replace(/\*\//g, '* /')}*/\n${parser}\nvar acorn = reviewParsers.acorn;\n  </script>\n  <!-- END EMBEDDED ACORN -->\n`;
const html = fs.readFileSync(file, 'utf8');
const marker = /  <!-- BEGIN EMBEDDED ACORN -->[\s\S]*?  <!-- END EMBEDDED ACORN -->\n/;
if (!marker.test(html)) throw new Error('Missing embedded parser marker');
let next = html.replace(marker, () => embedded);
const source = fs.readFileSync(path.join(root, 'src/checker.js'), 'utf8')
  .replace('      // EMBED JAVASCRIPT ANALYSIS', () => fs.readFileSync(path.join(root, 'src/javascript-analysis.js'), 'utf8').trimEnd())
  .replace('      // EMBED JAVA ANALYSIS', () => fs.readFileSync(path.join(root, 'src/java-analysis.js'), 'utf8').trimEnd());
if (/<\/script/i.test(source)) throw new Error('App source contains an unescaped HTML script terminator');
new (require('node:vm').Script)(source, { filename: 'checker.js' });
const appScript = /  <script>\n[\s\S]*?<\/script>(?=\n<\/body>)/;
// Select only the final script, avoiding the head's initial theme script.
const lastStart = next.lastIndexOf('  <script>');
if (lastStart < 0 || !appScript.test(next.slice(lastStart))) throw new Error('Missing final app script');
next = next.slice(0, lastStart) + next.slice(lastStart).replace(appScript, () => `  <script>\n${source}  </script>`);
if (process.argv.includes('--check')) {
  if (html !== next) {
    console.error('Embedded scripts differ from source or locked dependencies. Run npm run build:parser.');
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(file, next);
}
